export const products = [
  {
    id: 1,
    name: "Ananas",
    img: "ananas.jpeg",
    text: "den per kg",
    price: 200,
  },
  {
    id: 2,
    name: "Apples",
    img: "appels.jpeg",
    text: "den per kg",
    price: 100,
  },
  {
    id: 3,
    name: "Bananas",
    img: "bananas.jpeg",
    text: "den per kg",
    price: 100,
  },
  {
    id: 4,
    name: "Beans",
    img: "beans.jpeg",
    text: "den per kg",
    price: 50,
  },
  {
    id: 5,
    name: "Beer",
    img: "beer.jpeg",
    text: "den",
    price: 100,
  },
  {
    id: 6,
    name: "Cacao",
    img: "cacao.jpeg",
    text: "den",
    price: 50,
  },
  {
    id: 7,
    name: "Carrot",
    img: "carrot.jpeg",
    text: "den per kg",
    price: 60,
  },
  {
    id: 8,
    name: "Cherries",
    img: "cherries.jpeg",
    text: "den per kg",
    price: 200,
  },
  {
    id: 9,
    name: "Chips",
    img: "chips.jpeg",
    text: "den",
    price: 80,
  },
  {
    id: 10,
    name: "Chocolate",
    img: "chocolate.jpeg",
    text: "den",
    price: 60,
  },
  {
    id: 11,
    name: "Coca-Cola",
    img: "coca-cola.jpeg",
    text: "den",
    price: 60,
  },
  {
    id: 12,
    name: "Cucumber",
    img: "cucumber.jpeg",
    text: "den per kg",
    price: 50,
  },
  {
    id: 13,
    name: "Gin",
    img: "gin.jpeg",
    text: "den",
    price: 900,
  },
  {
    id: 14,
    name: "Kinder",
    img: "kinder.jpg",
    text: "den",
    price: 60,
  },
  {
    id: 15,
    name: "Lemons",
    img: "lemons.jpeg",
    text: "den",
    price: 60,
  },
  {
    id: 16,
    name: "Mango",
    img: "mango.jpeg",
    text: "den per kg",
    price: 160,
  },
  {
    id: 17,
    name: "Oranges",
    img: "oranges.jpeg",
    text: "den per kg",
    price: 100,
  },
  {
    id: 18,
    name: "Patato",
    img: "patato.jpeg",
    text: "den per kg",
    price: 60,
  },
  {
    id: 19,
    name: "Peach",
    img: "peach.jpeg",
    text: "den per kg",
    price: 90,
  },
  {
    id: 20,
    name: "Peppper",
    img: "piper.jpeg",
    text: "den per kg",
    price: 50,
  },
  {
    id: 21,
    name: "Tomato",
    img: "tomato.jpeg",
    text: "den per kg",
    price: 50,
  },
  {
    id: 22,
    name: "Wine",
    img: "wine.jpg",
    text: "den",
    price: 350,
  },
  {
    id: 23,
    name: "Nescafe",
    img: "nescoffee.jpeg",
    text: "den",
    price: 260,
  },
  {
    id: 24,
    name: "Water",
    img: "water.jpeg",
    text: "den",
    price: 50,
  },
];
